bloggy/urls.py
from django.contrib import admin
from django.urls import path, include
import posts 
urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
]

posts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('blog', views.index),
    # path('',  views.getPost,name='post'),
    path('<int:post_id>/post/', views.getPost, name='post'),
    path('categories/', views.getCategories, name='categories'),
    path('<int:category_id>/category/', views.getCategory, name='category'),
]

posts/models.py
from unicodedata import category
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class Category(models.Model):
    catName = models.CharField(max_length = 20)
    catDesc = models.TextField()
    def __str__(self):
        return self.title
class Post(models.Model):
    title = models.CharField(max_length = 20)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    
    def __str__(self):
        return self.title

    
class Comment(models.Model):
    text = models.TextField()
    cdate = models.DateField(auto_now = False)
    visible = models.BooleanField()
    def __str__(self):
        return self.title
    

posts/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.http import HttpResponse
from .models import Category, Post
# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'posts/posts.html', context)
    # output = ','.join([p.title for p in posts])
    # blogcontents = ','.join([p.content for p in posts])
    # context = {'titles': output, 'bcontents': blogcontents }
    # return HttpResponse(output)
    # return HttpResponse("Hello World! You're at the polls index.")
    
def getPost(request, post_id):
    post = Post.objects.get(id = post_id)
    context = {'post': post}
    return render(request, 'posts/post.html', context)

def getCategories(request):
    categories = Category.objects.all()
    context = {'categories': categories}
    return render(request, 'categories/categories.html', context)

def getCategory(request, category_id):
    category = Category.objects.get(id = category_id)
    context = {'category': category}
    return render(request, 'categories/category.html', context)

posts/templates/categories/categories.html
{% extends '../master.html' %}

{% block contents %}
    <table>
        <theader>
            <th>
                <tr>
                    <th>Category Name</th>
                    <th>Category Decscription</th>
                    <th>Category Posts</th>
                </tr>
            </th>
            {% for category in categories%}
                <tr>
                    <td>{{category.catName}}</td>
                    <td>{{category.catDesc}}</td>
                    <td>
                        {% for post in category.post_set.all%}
                            <li>{{post.title}}</li>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </theader>
    </table>

{% endblock contents %}

posts/templates/categories/category.html
{% extends '../master.html' %}

{% block contents %}
    <h1>{{category.catName}}</h1>
    <br>
    <h1>{{category.catDesc}}</h1>
{% endblock contents %}

posts/templates/master.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    <br>
    {% block contents %}{% endblock contents %}
    <br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

posts/templates/posts/post.html
{% extends '../master.html' %}

{% block contents %}
    <h1>{{post.title}}</h1>
    <br>
    <p>{{post.content}}</p>
{% endblock contents %}

posts/templates/posts/posts.html
{% extends '../master.html' %}

{% block contents %}
    <table>
        <theader>
            <th>
                <tr>
                    <th>Title</th>
                    <th>Content</th>
                </tr>
            </th>
            {% for post in posts%}
                <tr>
                    <td><a href= {% url 'post' post.id %}>{{post.title}}</a></td>
                    <td>{{post.content}}</td>
                </tr>
            {% endfor %}
        </theader>
    </table>

{% endblock contents %}